# Site settings
title: KIMI Blog
SEOTitle: 王琦玮的博客 | KIMI Blog
header-img: img/home-bg.jpg
email: wangqiwei366@gmail.com
description: "这里是 @王琦玮 的个人博客，与你一起发现更大的世界。"
keyword: "王琦玮, KIMI王琦玮, KIMI, 鬼栈, KIMIpro, @KIMIpro, 王琦玮的博客, KIMI Blog, 博客, 个人网站, 互联网, Web"
url: "https://wangqiwei366.github.io"
baseurl: ""

future: true
limit_posts: 3

# SNS settings
RSS: false
weibo_username: kimipro
zhihu_username: kimipro
github_username: wangqiwei366
twitter_username: kimipro

# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
  ]
anchorjs: true

plugins: [jekyll-paginate]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

disqus_username:
netease_comment: false
ga_track_id:
ga_domain: auto

sidebar: true
sidebar-about-description: ""
sidebar-avatar: /img/favicon-haibara.png

featured-tags: true
featured-condition-size: 1

chrome-tab-theme-color: "#000000"
service-worker: true
page-mathjax: false

friends:
  [
    { title: "Midare", href: "http://mida.re/" },
    { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
    { title: "Kun Qian", href: "http://kunq.me" },
    { title: "Sherry Woo", href: "https://sherrywoo.me/" },
    { title: "SmdCn", href: "http://blog.smdcn.net" },
    { title: "JiyinYiyong", href: "http://tiye.me/" },
    { title: "DHong Say", href: "http://dhong.co" },
    { title: "Ingf", href: "http://ingf.github.io/" },
  ]
